services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data:
